#!/usr/bin/env bash
# This script securely transfer a file from client to server
if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no "$1" "$2" "$3" "$4"
fi
