#!/usr/bin/env bash
# This script installs nginx on a web server
sudo apt-get update
sudo apt-get install -y nginx
echo 'hello Holberton School' | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
