#!/usr/bin/env bash
# This script installs nginx on a web server
sudo apt-get -y install nginx
sudo service nginx start
echo 'Holberton School for the win!' > /usr/share/nginx/html/index.html
sudo service nginx restart
