#!/usr/bin/env bash
# This script installs nginx and redirects to custom 301 page
# sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start ubuntu@66.70.184.164
sudo touch /usr/share/nginx/html/redirect_me
sudo sed -i '26 i \ \trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart ubuntu@66.70.184.164
