#!/usr/bin/env bash
# This script installs nginx and redirects to custom 301 page
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo sed -i '31 i \ \trewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
