#!/usr/bin/env bash
#This script displays information about reconfigured subdomains
#shellcheck disable=SC2086

domain="$1"
subdomain="$2"
result=$(dig $domain $subdomain | grep -A1 'ANSWER SECTION:' | cut -d ':' -f2-)
record_type=$(awk '{ print $4 }' <<< $result)
destination=$(awk '{ print $5 }' <<< $result)

if [ -z "$2" ]
    then
        echo "The subdomain" $domain "is a" $record_type "record and points to" $destination
    else
        echo "The subdomain" $subdomain "is a" $record_type "record and points to" $destination
    fi
