#!/usr/bin/env bash
#This script displays information about reconfigured subdomains
#shellcheck disable=SC2086

stringFormat () {
    domain="$1"
    subdomain="$2"
    result=$(dig $subdomain.$domain | grep -A1 'ANSWER SECTION:' | cut -d ':' -f2-)
    record_type=$(awk '{ print $4 }' <<< $result)
    destination=$(awk '{ print $5 }' <<< $result)
    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]
then
    stringFormat "$domain" "www"
    stringFormat "$domain" "lb-01"
    stringFormat "$domain" "web-01"
    stringFormat "$domain" "web-02"
else
    stringFormat "$domain" "$subdomain"
fi
