#!/usr/bin/env bash
# This script creates a file containing this processes PID
# and handles various signals

echo $$ > /var/run/holbertonscript.pid

while true
do
    trap 'echo I hate the kill command' SIGTERM
    trap 'echo Y u no love me?!' SIGINT

    if [[ $SIGQUIT || $SIGKILL ]]
    then
	sudo rm -f /var/run/holbertonscript.pid
    else
	echo 'To infinity and beyond'
    fi
done
