#!/usr/bin/env bash
# Displays numbers from 1 to 100
# For multiples of 3 and 5 - print 'FizzBuzz'
# For multiples of 3 - print 'Fizz'
# For multiple of 5 - print 'Buzz'

for i in {1..100}; do
    if ((i % 3 == 0)) && ((i % 5 == 0))
    then
	echo 'FizzBuzz'
    elif ((i % 3 == 0))
    then
	echo 'Fizz'
    elif ((i % 5 == 0))
    then
	echo 'Buzz'
    else
        echo $i

    fi
done
