#!/usr/bin/env bash
# This script displays "Holberton School" 10 times
# And on 9th iteration dispays "Hi"

i=0
school_name="Holberton School"
while [ $i -lt 10 ]; do
    if [ $i == 9 ]
    then
	echo "Hi"
    fi
	echo "$school_name"
    let i+=1
done
