#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

i=0
school_name="Holberton School"
while [ $i -lt 10 ]; do
    if [ $i == 9 ]
    then
	echo "Hi"
    fi
	echo "$school_name"
    let i+=1
done
