#!/usr/bin/env bash
# This script displays iteration number
# unless it is a specified iteration number -
# i.e (4) displays "bad luck from China"
# (8) displays "bad luck from Japan"
# (17) displays "bad luck from Italy"

i=1
while [ $i -le 20 ]; do
    echo $i

    case "$i" in
	4)
	echo "bad luck from China"
	;;
	9)
	echo "bad luck from Japan"
	;;
	17)
	echo "bad luck from Italy"
	;;
    esac

    let i+=1
done
