#!/usr/bin/env bash
# Script provides information about a specific file
# Checks if file exists
# If so, prints different information depending on file contents

if [ -e 'holbertonschool' ]
then
    echo 'holbertonschool file exists'

    if [ -s 'holbertonschool' ]
    then
	echo 'holbertonschool file is not empty'
    else
	echo 'holbertonschool file is empty'
    fi

    if [ -r 'holbertonschool' ]
    then
	echo 'holbertonschool is a regular file'
    fi

else
    echo 'holbertonschool file does not exist'
fi
