#!/usr/bin/env bash
# This script configures an Ubuntu with modified IP resolution
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
sudo echo '8.8.8.8    facebook.com' | sudo tee -a /etc/hosts
