#!/usr/bin/env bash
# Script that configured brand new web server on an Ubuntu machine
# sets custom http response header
# shellcheck disable=SC2154
# sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
echo 'add_header X-Served-By: $hostname' | sudo tee /etc/nginx/nginx.conf
sudo service nginx restart
