#!/usr/bin/env bash
# Script that configured brand new web server on an Ubuntu machine
# sets custom http response header
# shellcheck disable=SC2154
# sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
sudo sed -i '16 i \ add_header X-Served-By: $HOSTNAME' /etc/nginx/nginx.conf
sudo service nginx restart
