#!/usr/bin/env bash
# Script that installs and configures HAproxy load balancer on new server
# sets custom http response header
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.5
sudo apt-get update
sudo apt-get install haproxy
sudo service haproxy start
sudo sed -i '8 i ENABLED=1' /etc/default/haproxy
string='listen Holberton-HAProxy *:80\n\tmode http\n\tstats enable\n\tstats uri /haproxy?status\n\t
balance roundrobin\n\tserver 128-web-01 66.70.184.164:80 check\n\tserver 128-web-02 142.44.164.121:80 check'
sudo sed -i '25 i $string' /etc/haproxy/haproxy.cfg
sudo service haproxy reload
