#!/usr/bin/env bash
# Script that installs and configures HAproxy load balancer on new server
# sets custom http response header
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.5
sudo apt-get update
sudo apt-get -y install haproxy
listen_string='\nlisten Holberton-HAProxy *:80\n\tmode http\n\tstats enable\n\tstats uri /haproxy?status\n\tbalance roundrobin\n\tserver 128-web-01 66.70.184.164:80 check\n\tserver 128-web-02 142.44.164.121:80 check'
sudo sed -i '1 i ENABLED=1' /etc/default/haproxy
sudo echo -e "$listen_string" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
