#!/usr/bin/env bash
# Configure nginx to run as nginx user rather than root
# This is for security purposes - if server is hacked / security breached
# The hacker is limited by the permissions of nginx user as opposed to root(su)
sed -i '4i user nginx;' /etc/nginx/nginx.conf
sed -i 'i s/768/1024g' /etc/nginx/nginx.conf
pkill apache2
service nginx restart
